Repository retest/docs, pull requests merged in 2019-09, with the labels that each got.

#37 Feature/doc changes
  docs/recheck-web/element-identification-problem.md
  docs/recheck-web/postpone-test-breakage.md
  docs/recheck-web/setup/maven.md
  docs/recheck-web/tutorial/explicit-checks.md
  docs/recheck-web/tutorial/rule-based-ignore.md
  docs/recheck-web/tutorial/setup-recheck.ignore.md
  docs/recheck-web/tutorial/travis-execute-ci.md
  docs/recheck-web/tutorial/upload-test-reports-to-rehub.md
  docs/recheck-web/tutorial/using-git-and-github.md
  docs/recheck-web/unbreakable-selenium.md
Labels: cla-signed

#38 Improve docs
  docs/recheck-web/tutorial/upload-test-reports-to-rehub.md
Labels: cla-signed

#40 Update recheck.cli version in codeblocks
  docs/recheck.cli/setup.md
Labels: cla-signed

#42 Feature/recheck intro
  docs/recheck/introduction/index.md
  docs/recheck/introduction/installation.md
  mkdocs.yml
Labels: cla-signed

#45 Ignore the vscode directory
  .gitignore
Labels: cla-signed

#47 feature/redirect from old to new sites
  .travis.yml
  mkdocs.yml
Labels: bug, cla-signed

#43 Feature/recheck usage
  docs/recheck/introduction/usage.md
  docs/recheck/reuse-golden-master-files.md
  mkdocs.yml
Labels: cla-signed

#48 Feature/update doc
  docs/misc/gsoc.md
  docs/recheck-web/contributor-information.md
  docs/recheck-web/setup/maven.md
  docs/recheck-web/tutorial/explicit-checks.md
  docs/recheck-web/ways-of-using-recheck-web.md
  docs/recheck/how-ignore-works.md
  docs/recheck/introduction/usage.md
  docs/recheck/location-of-the-golden-master-files-and-test-reports.md
  docs/recheck/recheck-options.md
  mkdocs.yml
Labels: cla-signed

#46 Feature/use tabs for products
  mkdocs.yml
Labels: cla-signed

#50 Misc
  docs/recheck/how-ignore-works.md
  docs/recheck/introduction/installation.md
  docs/recheck/introduction/usage.md
Labels: cla-signed

#51 Feature/recheck config filters
  .travis.yml
  docs/recheck/how-ignore-works.md
  docs/recheck/introduction/usage.md
  docs/recheck/location-of-the-golden-master-files-and-test-reports.md
  docs/recheck/properties.md
  docs/recheck/recheck-options.md
  docs/recheck/usage/configuration.md
  docs/recheck/usage/filter.md
  mkdocs.yml
Labels: cla-signed, enhancement
